#
# Generated by "infrahubctl protocols"
#

from __future__ import annotations

from typing import TYPE_CHECKING

from infrahub_sdk.protocols import (
    BuiltinIPAddress,
    BuiltinIPPrefix,
    CoreArtifactTarget,
    CoreNode,
)

if TYPE_CHECKING:
    from infrahub_sdk.node import RelatedNodeSync, RelationshipManagerSync
    from infrahub_sdk.protocols_base import (
        Boolean,
        Dropdown,
        DropdownOptional,
        Integer,
        IntegerOptional,
        String,
        StringOptional,
    )


class DcimConnector(CoreNode):
    connected_endpoints: RelationshipManagerSync


class DcimEndpoint(CoreNode):
    connector: RelatedNodeSync


class ServiceGeneric(CoreNode):
    service_identifier: String
    account_reference: String


class OrganizationGeneric(CoreNode):
    name: String
    description: StringOptional
    tags: RelationshipManagerSync


class LocationGeneric(CoreNode):
    name: String
    shortname: String
    description: StringOptional
    tags: RelationshipManagerSync


class DcimGenericDevice(CoreNode):
    name: String
    description: StringOptional
    os_version: StringOptional
    interfaces: RelationshipManagerSync
    tags: RelationshipManagerSync
    primary_address: RelatedNodeSync
    platform: RelatedNodeSync


class LocationHosting(CoreNode):
    shortname: String
    prefixes: RelationshipManagerSync
    devices: RelationshipManagerSync


class DcimInterface(CoreNode):
    name: String
    description: StringOptional
    speed: Integer
    mtu: Integer
    enabled: Boolean
    device: RelatedNodeSync
    tags: RelationshipManagerSync


class DcimPhysicalDevice(CoreNode):
    position: IntegerOptional
    serial: StringOptional
    rack_face: Dropdown
    device_type: RelatedNodeSync
    location: RelatedNodeSync


class LocationCountry(LocationGeneric):
    timezone: StringOptional


class ServiceDedicatedInternet(ServiceGeneric):
    status: Dropdown
    bandwidth: Dropdown
    ip_package: Dropdown
    location: RelatedNodeSync
    dedicated_interfaces: RelationshipManagerSync
    vlan: RelatedNodeSync
    gateway_ip_address: RelatedNodeSync
    prefix: RelatedNodeSync


class DcimDevice(CoreArtifactTarget, DcimGenericDevice, DcimPhysicalDevice):
    status: Dropdown
    role: DropdownOptional
    index: IntegerOptional


class DcimDeviceType(CoreNode):
    name: String
    description: StringOptional
    part_number: StringOptional
    height: Integer
    full_depth: Boolean
    weight: IntegerOptional
    platform: RelatedNodeSync
    manufacturer: RelatedNodeSync
    tags: RelationshipManagerSync


class IpamIPAddress(BuiltinIPAddress):
    fqdn: StringOptional
    interface: RelatedNodeSync


class DcimInterfaceL2(DcimInterface, DcimEndpoint):
    role: DropdownOptional
    status: DropdownOptional
    l2_mode: StringOptional


class DcimInterfaceL3(DcimInterface, DcimEndpoint):
    role: DropdownOptional
    status: DropdownOptional
    ip_addresses: RelationshipManagerSync


class IpamL2Domain(CoreNode):
    name: String
    vlans: RelationshipManagerSync


class OrganizationManufacturer(OrganizationGeneric):
    device_type: RelationshipManagerSync
    platform: RelationshipManagerSync


class LocationMetro(LocationGeneric):
    pass


class DcimPlatform(CoreNode):
    name: String
    description: StringOptional
    nornir_platform: StringOptional
    napalm_driver: StringOptional
    netmiko_device_type: StringOptional
    ansible_network_os: StringOptional
    containerlab_os: StringOptional
    devices: RelationshipManagerSync
    manufacturer: RelatedNodeSync


class IpamPrefix(BuiltinIPPrefix):
    status: Dropdown
    role: DropdownOptional
    organization: RelatedNodeSync
    location: RelatedNodeSync
    gateway: RelatedNodeSync


class OrganizationProvider(OrganizationGeneric):
    pass


class LocationRack(LocationGeneric, LocationHosting):
    facility_id: StringOptional
    height: Integer
    owner: RelatedNodeSync


class LocationSite(LocationGeneric, LocationHosting):
    facility_id: StringOptional
    physical_address: StringOptional
    owner: RelatedNodeSync


class IpamVLAN(CoreNode):
    name: String
    description: StringOptional
    vlan_id: Integer
    status: Dropdown
    role: DropdownOptional
    location: RelationshipManagerSync
    prefixes: RelationshipManagerSync
    l2domain: RelatedNodeSync
