#
# Generated by "infrahubctl protocols"
#

from __future__ import annotations

from typing import TYPE_CHECKING

from infrahub_sdk.protocols import (
    BuiltinIPAddress,
    BuiltinIPPrefix,
    CoreArtifactTarget,
    CoreNode,
    CoreObjectTemplate,
    CoreProfile,
    LineageSource,
)

if TYPE_CHECKING:
    from infrahub_sdk.node import RelatedNode, RelationshipManager
    from infrahub_sdk.protocols_base import (
        BooleanOptional,
        Dropdown,
        DropdownOptional,
        Integer,
        IntegerOptional,
        IPHost,
        IPNetwork,
        String,
        StringOptional,
    )


class DcimConnector(CoreNode):
    connected_endpoints: RelationshipManager
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class TemplateDcimGenericDevice(CoreNode):
    template_name: String
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class TemplateDcimInterface(CoreNode):
    template_name: String
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimEndpoint(CoreNode):
    connector: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class LocationGeneric(CoreNode):
    description: StringOptional
    name: String
    shortname: String
    children: RelationshipManager
    member_of_groups: RelationshipManager
    parent: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class OrganizationGeneric(CoreNode):
    description: StringOptional
    name: String
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class ServiceGeneric(CoreNode):
    account_reference: String
    service_identifier: String
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimGenericDevice(CoreNode):
    description: StringOptional
    name: String
    os_version: StringOptional
    interfaces: RelationshipManager
    member_of_groups: RelationshipManager
    platform: RelatedNode
    primary_address: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class LocationHosting(CoreNode):
    shortname: String
    devices: RelationshipManager
    member_of_groups: RelationshipManager
    prefixes: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    vlans: RelationshipManager


class DcimInterface(CoreNode):
    description: StringOptional
    enabled: BooleanOptional
    mtu: IntegerOptional
    name: String
    speed: Integer
    device: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    service: RelatedNode
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class CoreObjectComponentTemplate(CoreNode):
    template_name: String
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimPhysicalDevice(CoreNode):
    position: IntegerOptional
    rack_face: DropdownOptional
    serial: StringOptional
    device_type: RelatedNode
    location: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class LocationCountry(LocationGeneric):
    description: StringOptional
    name: String
    shortname: String
    timezone: StringOptional
    children: RelationshipManager
    member_of_groups: RelationshipManager
    parent: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class ServiceDedicatedInternet(ServiceGeneric):
    account_reference: String
    bandwidth: Dropdown
    ip_package: Dropdown
    service_identifier: String
    status: DropdownOptional
    dedicated_interfaces: RelationshipManager
    gateway_ip_address: RelatedNode
    location: RelatedNode
    member_of_groups: RelationshipManager
    prefix: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    vlan: RelatedNode


class DcimDevice(CoreArtifactTarget, DcimGenericDevice, DcimPhysicalDevice):
    description: StringOptional
    index: IntegerOptional
    name: String
    os_version: StringOptional
    position: IntegerOptional
    rack_face: DropdownOptional
    role: DropdownOptional
    serial: StringOptional
    status: Dropdown
    artifacts: RelationshipManager
    device_type: RelatedNode
    interfaces: RelationshipManager
    location: RelatedNode
    member_of_groups: RelationshipManager
    object_template: RelatedNode
    platform: RelatedNode
    primary_address: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class DcimDeviceType(CoreNode):
    description: StringOptional
    full_depth: BooleanOptional
    height: IntegerOptional
    name: String
    part_number: StringOptional
    weight: IntegerOptional
    manufacturer: RelatedNode
    member_of_groups: RelationshipManager
    platform: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class IpamIPAddress(BuiltinIPAddress):
    address: IPHost
    description: StringOptional
    fqdn: StringOptional
    interface: RelatedNode
    ip_namespace: RelatedNode
    ip_prefix: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    service: RelatedNode
    subscriber_of_groups: RelationshipManager


class DcimInterfaceL2(DcimInterface, DcimEndpoint):
    description: StringOptional
    enabled: BooleanOptional
    l2_mode: StringOptional
    mtu: IntegerOptional
    name: String
    role: DropdownOptional
    speed: Integer
    status: DropdownOptional
    connector: RelatedNode
    device: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    service: RelatedNode
    subscriber_of_groups: RelationshipManager
    tagged_vlan: RelationshipManager
    tags: RelationshipManager
    untagged_vlan: RelatedNode


class DcimInterfaceL3(DcimInterface, DcimEndpoint):
    description: StringOptional
    enabled: BooleanOptional
    mtu: IntegerOptional
    name: String
    role: DropdownOptional
    speed: Integer
    status: DropdownOptional
    connector: RelatedNode
    device: RelatedNode
    ip_addresses: RelationshipManager
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    service: RelatedNode
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class IpamL2Domain(CoreNode):
    name: String
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    vlans: RelationshipManager


class OrganizationManufacturer(OrganizationGeneric):
    description: StringOptional
    name: String
    device_type: RelationshipManager
    member_of_groups: RelationshipManager
    platform: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class LocationMetro(LocationGeneric):
    description: StringOptional
    name: String
    shortname: String
    children: RelationshipManager
    member_of_groups: RelationshipManager
    parent: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class DcimPlatform(CoreNode):
    ansible_network_os: StringOptional
    containerlab_os: StringOptional
    description: StringOptional
    name: String
    napalm_driver: StringOptional
    netmiko_device_type: StringOptional
    nornir_platform: StringOptional
    devices: RelationshipManager
    manufacturer: RelatedNode
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class IpamPrefix(BuiltinIPPrefix):
    broadcast_address: StringOptional
    description: StringOptional
    hostmask: StringOptional
    is_pool: BooleanOptional
    is_top_level: BooleanOptional
    member_type: DropdownOptional
    netmask: StringOptional
    network_address: StringOptional
    prefix: IPNetwork
    role: DropdownOptional
    status: Dropdown
    utilization: IntegerOptional
    children: RelationshipManager
    gateway: RelatedNode
    ip_addresses: RelationshipManager
    ip_namespace: RelatedNode
    location: RelatedNode
    member_of_groups: RelationshipManager
    organization: RelatedNode
    parent: RelatedNode
    profiles: RelationshipManager
    resource_pool: RelationshipManager
    service: RelatedNode
    subscriber_of_groups: RelationshipManager
    vlan: RelatedNode


class OrganizationProvider(OrganizationGeneric):
    description: StringOptional
    name: String
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    sites: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class LocationRack(LocationGeneric, LocationHosting):
    description: StringOptional
    facility_id: StringOptional
    height: IntegerOptional
    name: String
    shortname: String
    children: RelationshipManager
    devices: RelationshipManager
    member_of_groups: RelationshipManager
    owner: RelatedNode
    parent: RelatedNode
    prefixes: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager
    vlans: RelationshipManager


class LocationSite(LocationGeneric, LocationHosting):
    description: StringOptional
    facility_id: StringOptional
    name: String
    physical_address: StringOptional
    shortname: String
    children: RelationshipManager
    devices: RelationshipManager
    member_of_groups: RelationshipManager
    owner: RelatedNode
    parent: RelatedNode
    prefixes: RelationshipManager
    profiles: RelationshipManager
    services: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager
    vlans: RelationshipManager


class IpamVLAN(CoreNode):
    description: StringOptional
    name: String
    role: DropdownOptional
    status: Dropdown
    vlan_id: Integer
    l2domain: RelatedNode
    location: RelationshipManager
    member_of_groups: RelationshipManager
    prefixes: RelationshipManager
    profiles: RelationshipManager
    service: RelatedNode
    subscriber_of_groups: RelationshipManager


class ProfileBuiltinIPAddress(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileBuiltinIPPrefix(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    is_pool: BooleanOptional
    member_type: DropdownOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileBuiltinTag(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimConnector(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimDevice(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    index: IntegerOptional
    os_version: StringOptional
    position: IntegerOptional
    profile_name: String
    profile_priority: IntegerOptional
    rack_face: DropdownOptional
    role: DropdownOptional
    serial: StringOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimDeviceType(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    full_depth: BooleanOptional
    height: IntegerOptional
    part_number: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    weight: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimEndpoint(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimGenericDevice(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    os_version: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimInterface(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    enabled: BooleanOptional
    mtu: IntegerOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimInterfaceL2(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    enabled: BooleanOptional
    l2_mode: StringOptional
    mtu: IntegerOptional
    profile_name: String
    profile_priority: IntegerOptional
    role: DropdownOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimInterfaceL3(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    enabled: BooleanOptional
    mtu: IntegerOptional
    profile_name: String
    profile_priority: IntegerOptional
    role: DropdownOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimPhysicalDevice(LineageSource, CoreProfile, CoreNode):
    position: IntegerOptional
    profile_name: String
    profile_priority: IntegerOptional
    rack_face: DropdownOptional
    serial: StringOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimPlatform(LineageSource, CoreProfile, CoreNode):
    ansible_network_os: StringOptional
    containerlab_os: StringOptional
    description: StringOptional
    napalm_driver: StringOptional
    netmiko_device_type: StringOptional
    nornir_platform: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileIpamIPAddress(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    fqdn: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileIpamL2Domain(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileIpamNamespace(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileIpamPrefix(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    is_pool: BooleanOptional
    member_type: DropdownOptional
    profile_name: String
    profile_priority: IntegerOptional
    role: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileIpamVLAN(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    role: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationCountry(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    timezone: StringOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationGeneric(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationHosting(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationMetro(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationRack(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    facility_id: StringOptional
    height: IntegerOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationSite(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    facility_id: StringOptional
    physical_address: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileOrganizationGeneric(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileOrganizationManufacturer(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileOrganizationProvider(LineageSource, CoreProfile, CoreNode):
    description: StringOptional
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceDedicatedInternet(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    status: DropdownOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceGeneric(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager


class TemplateDcimDevice(LineageSource, TemplateDcimGenericDevice, CoreObjectTemplate, CoreNode):
    description: StringOptional
    index: IntegerOptional
    os_version: StringOptional
    position: IntegerOptional
    rack_face: DropdownOptional
    role: DropdownOptional
    serial: StringOptional
    status: DropdownOptional
    template_name: String
    artifacts: RelationshipManager
    device_type: RelatedNode
    interfaces: RelationshipManager
    location: RelatedNode
    member_of_groups: RelationshipManager
    platform: RelatedNode
    primary_address: RelatedNode
    related_nodes: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class TemplateDcimInterfaceL2(LineageSource, CoreObjectComponentTemplate, TemplateDcimInterface, CoreNode):
    description: StringOptional
    enabled: BooleanOptional
    l2_mode: StringOptional
    mtu: IntegerOptional
    name: String
    role: DropdownOptional
    speed: Integer
    status: DropdownOptional
    template_name: String
    connector: RelatedNode
    device: RelatedNode
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    service: RelatedNode
    subscriber_of_groups: RelationshipManager
    tagged_vlan: RelationshipManager
    tags: RelationshipManager
    untagged_vlan: RelatedNode


class TemplateDcimInterfaceL3(LineageSource, CoreObjectComponentTemplate, TemplateDcimInterface, CoreNode):
    description: StringOptional
    enabled: BooleanOptional
    mtu: IntegerOptional
    name: String
    role: DropdownOptional
    speed: Integer
    status: DropdownOptional
    template_name: String
    connector: RelatedNode
    device: RelatedNode
    ip_addresses: RelationshipManager
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    service: RelatedNode
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class TemplateIpamIPAddress(LineageSource, CoreObjectComponentTemplate, CoreNode):
    address: IPHost
    description: StringOptional
    fqdn: StringOptional
    template_name: String
    interface: RelatedNode
    ip_namespace: RelatedNode
    ip_prefix: RelatedNode
    member_of_groups: RelationshipManager
    related_nodes: RelationshipManager
    service: RelatedNode
    subscriber_of_groups: RelationshipManager


class TemplateIpamVLAN(LineageSource, CoreObjectComponentTemplate, CoreNode):
    description: StringOptional
    name: String
    role: DropdownOptional
    status: Dropdown
    template_name: String
    vlan_id: Integer
    l2domain: RelatedNode
    location: RelationshipManager
    member_of_groups: RelationshipManager
    prefixes: RelationshipManager
    related_nodes: RelationshipManager
    service: RelatedNode
    subscriber_of_groups: RelationshipManager
