#
# Generated by "infrahubctl protocols"
#

from __future__ import annotations

from typing import TYPE_CHECKING

from infrahub_sdk.protocols import (
    BuiltinIPAddress,
    BuiltinIPPrefix,
    CoreArtifactTarget,
    CoreNode,
    CoreObjectTemplate,
    CoreProfile,
    LineageSource,
)

if TYPE_CHECKING:
    from infrahub_sdk.node import RelatedNode, RelationshipManager
    from infrahub_sdk.protocols_base import (
        BooleanOptional,
        Dropdown,
        DropdownOptional,
        Integer,
        IntegerOptional,
        IPHost,
        IPNetwork,
        String,
        StringOptional,
    )


class DcimConnector(CoreNode):
    profiles: RelationshipManager
    connected_endpoints: RelationshipManager
    subscriber_of_groups: RelationshipManager
    member_of_groups: RelationshipManager


class TemplateDcimGenericDevice(CoreNode):
    template_name: String
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class TemplateDcimInterface(CoreNode):
    template_name: String
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimEndpoint(CoreNode):
    connector: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    member_of_groups: RelationshipManager


class LocationGeneric(CoreNode):
    shortname: String
    name: String
    description: StringOptional
    parent: RelatedNode
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager
    children: RelationshipManager
    profiles: RelationshipManager
    tags: RelationshipManager


class OrganizationGeneric(CoreNode):
    description: StringOptional
    name: String
    subscriber_of_groups: RelationshipManager
    profiles: RelationshipManager
    tags: RelationshipManager
    member_of_groups: RelationshipManager


class ServiceGeneric(CoreNode):
    account_reference: String
    service_identifier: String
    member_of_groups: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimGenericDevice(CoreNode):
    name: String
    description: StringOptional
    os_version: StringOptional
    platform: RelatedNode
    tags: RelationshipManager
    primary_address: RelatedNode
    member_of_groups: RelationshipManager
    interfaces: RelationshipManager
    subscriber_of_groups: RelationshipManager
    profiles: RelationshipManager


class LocationHosting(CoreNode):
    shortname: String
    prefixes: RelationshipManager
    subscriber_of_groups: RelationshipManager
    profiles: RelationshipManager
    member_of_groups: RelationshipManager
    devices: RelationshipManager
    vlans: RelationshipManager


class DcimInterface(CoreNode):
    description: StringOptional
    speed: Integer
    enabled: BooleanOptional
    mtu: IntegerOptional
    name: String
    tags: RelationshipManager
    member_of_groups: RelationshipManager
    device: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    service: RelatedNode


class CoreObjectComponentTemplate(CoreNode):
    template_name: String
    subscriber_of_groups: RelationshipManager
    member_of_groups: RelationshipManager


class DcimPhysicalDevice(CoreNode):
    serial: StringOptional
    position: IntegerOptional
    rack_face: DropdownOptional
    profiles: RelationshipManager
    device_type: RelatedNode
    location: RelatedNode
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class LocationCountry(LocationGeneric):
    shortname: String
    name: String
    description: StringOptional
    timezone: StringOptional
    children: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    member_of_groups: RelationshipManager
    parent: RelatedNode
    tags: RelationshipManager


class ServiceDedicatedInternet(ServiceGeneric):
    ip_package: Dropdown
    bandwidth: Dropdown
    status: DropdownOptional
    account_reference: String
    service_identifier: String
    location: RelatedNode
    member_of_groups: RelationshipManager
    dedicated_interfaces: RelationshipManager
    gateway_ip_address: RelatedNode
    prefix: RelatedNode
    vlan: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager


class DcimDevice(CoreArtifactTarget, DcimGenericDevice, DcimPhysicalDevice):
    index: IntegerOptional
    status: Dropdown
    role: DropdownOptional
    name: String
    description: StringOptional
    os_version: StringOptional
    serial: StringOptional
    position: IntegerOptional
    rack_face: DropdownOptional
    profiles: RelationshipManager
    object_template: RelatedNode
    artifacts: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager
    platform: RelatedNode
    tags: RelationshipManager
    primary_address: RelatedNode
    interfaces: RelationshipManager
    device_type: RelatedNode
    location: RelatedNode


class DcimDeviceType(CoreNode):
    height: IntegerOptional
    description: StringOptional
    full_depth: BooleanOptional
    weight: IntegerOptional
    part_number: StringOptional
    name: String
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager
    member_of_groups: RelationshipManager
    platform: RelatedNode
    manufacturer: RelatedNode
    profiles: RelationshipManager


class IpamIPAddress(BuiltinIPAddress):
    fqdn: StringOptional
    description: StringOptional
    address: IPHost
    service: RelatedNode
    interface: RelatedNode
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    ip_namespace: RelatedNode
    member_of_groups: RelationshipManager
    ip_prefix: RelatedNode


class DcimInterfaceL2(DcimInterface, DcimEndpoint):
    status: DropdownOptional
    role: DropdownOptional
    l2_mode: StringOptional
    description: StringOptional
    speed: Integer
    enabled: BooleanOptional
    mtu: IntegerOptional
    name: String
    subscriber_of_groups: RelationshipManager
    profiles: RelationshipManager
    untagged_vlan: RelatedNode
    member_of_groups: RelationshipManager
    tagged_vlan: RelationshipManager
    tags: RelationshipManager
    device: RelatedNode
    service: RelatedNode
    connector: RelatedNode


class DcimInterfaceL3(DcimInterface, DcimEndpoint):
    role: DropdownOptional
    status: DropdownOptional
    description: StringOptional
    speed: Integer
    enabled: BooleanOptional
    mtu: IntegerOptional
    name: String
    subscriber_of_groups: RelationshipManager
    ip_addresses: RelationshipManager
    profiles: RelationshipManager
    member_of_groups: RelationshipManager
    tags: RelationshipManager
    device: RelatedNode
    service: RelatedNode
    connector: RelatedNode


class IpamL2Domain(CoreNode):
    name: String
    profiles: RelationshipManager
    vlans: RelationshipManager
    subscriber_of_groups: RelationshipManager
    member_of_groups: RelationshipManager


class OrganizationManufacturer(OrganizationGeneric):
    description: StringOptional
    name: String
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager
    device_type: RelationshipManager
    platform: RelationshipManager
    profiles: RelationshipManager
    tags: RelationshipManager


class LocationMetro(LocationGeneric):
    shortname: String
    name: String
    description: StringOptional
    children: RelationshipManager
    profiles: RelationshipManager
    parent: RelatedNode
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class DcimPlatform(CoreNode):
    nornir_platform: StringOptional
    netmiko_device_type: StringOptional
    napalm_driver: StringOptional
    ansible_network_os: StringOptional
    containerlab_os: StringOptional
    name: String
    description: StringOptional
    manufacturer: RelatedNode
    devices: RelationshipManager
    subscriber_of_groups: RelationshipManager
    member_of_groups: RelationshipManager
    profiles: RelationshipManager


class IpamPrefix(BuiltinIPPrefix):
    status: Dropdown
    role: DropdownOptional
    netmask: StringOptional
    network_address: StringOptional
    description: StringOptional
    utilization: IntegerOptional
    member_type: DropdownOptional
    is_top_level: BooleanOptional
    prefix: IPNetwork
    broadcast_address: StringOptional
    hostmask: StringOptional
    is_pool: BooleanOptional
    service: RelatedNode
    vlan: RelatedNode
    organization: RelatedNode
    gateway: RelatedNode
    location: RelatedNode
    member_of_groups: RelationshipManager
    resource_pool: RelationshipManager
    ip_addresses: RelationshipManager
    ip_namespace: RelatedNode
    children: RelationshipManager
    subscriber_of_groups: RelationshipManager
    profiles: RelationshipManager
    parent: RelatedNode


class OrganizationProvider(OrganizationGeneric):
    description: StringOptional
    name: String
    member_of_groups: RelationshipManager
    sites: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    tags: RelationshipManager


class LocationRack(LocationGeneric, LocationHosting):
    height: IntegerOptional
    facility_id: StringOptional
    shortname: String
    name: String
    description: StringOptional
    parent: RelatedNode
    children: RelationshipManager
    subscriber_of_groups: RelationshipManager
    owner: RelatedNode
    profiles: RelationshipManager
    member_of_groups: RelationshipManager
    tags: RelationshipManager
    prefixes: RelationshipManager
    devices: RelationshipManager
    vlans: RelationshipManager


class LocationSite(LocationGeneric, LocationHosting):
    facility_id: StringOptional
    physical_address: StringOptional
    shortname: String
    name: String
    description: StringOptional
    children: RelationshipManager
    profiles: RelationshipManager
    subscriber_of_groups: RelationshipManager
    member_of_groups: RelationshipManager
    parent: RelatedNode
    services: RelationshipManager
    owner: RelatedNode
    tags: RelationshipManager
    prefixes: RelationshipManager
    devices: RelationshipManager
    vlans: RelationshipManager


class IpamVLAN(CoreNode):
    role: DropdownOptional
    name: String
    vlan_id: Integer
    status: Dropdown
    description: StringOptional
    subscriber_of_groups: RelationshipManager
    member_of_groups: RelationshipManager
    service: RelatedNode
    prefixes: RelationshipManager
    location: RelationshipManager
    l2domain: RelatedNode
    profiles: RelationshipManager


class ProfileBuiltinIPAddress(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    description: StringOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileBuiltinIPPrefix(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    description: StringOptional
    member_type: DropdownOptional
    is_pool: BooleanOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileBuiltinTag(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    description: StringOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimConnector(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimDevice(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    index: IntegerOptional
    role: DropdownOptional
    description: StringOptional
    os_version: StringOptional
    serial: StringOptional
    position: IntegerOptional
    rack_face: DropdownOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimDeviceType(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    height: IntegerOptional
    description: StringOptional
    full_depth: BooleanOptional
    weight: IntegerOptional
    part_number: StringOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimEndpoint(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimGenericDevice(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    description: StringOptional
    os_version: StringOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimInterface(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    description: StringOptional
    enabled: BooleanOptional
    mtu: IntegerOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimInterfaceL2(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    status: DropdownOptional
    role: DropdownOptional
    l2_mode: StringOptional
    description: StringOptional
    enabled: BooleanOptional
    mtu: IntegerOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimInterfaceL3(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    role: DropdownOptional
    status: DropdownOptional
    description: StringOptional
    enabled: BooleanOptional
    mtu: IntegerOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimPhysicalDevice(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    serial: StringOptional
    position: IntegerOptional
    rack_face: DropdownOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileDcimPlatform(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    nornir_platform: StringOptional
    netmiko_device_type: StringOptional
    napalm_driver: StringOptional
    ansible_network_os: StringOptional
    containerlab_os: StringOptional
    description: StringOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileIpamIPAddress(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    fqdn: StringOptional
    description: StringOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileIpamL2Domain(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileIpamNamespace(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    description: StringOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileIpamPrefix(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    role: DropdownOptional
    description: StringOptional
    member_type: DropdownOptional
    is_pool: BooleanOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileIpamVLAN(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    role: DropdownOptional
    description: StringOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationCountry(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    timezone: StringOptional
    description: StringOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationGeneric(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    description: StringOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationHosting(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationMetro(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    description: StringOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationRack(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    height: IntegerOptional
    facility_id: StringOptional
    description: StringOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileLocationSite(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    facility_id: StringOptional
    physical_address: StringOptional
    description: StringOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileOrganizationGeneric(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    description: StringOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileOrganizationManufacturer(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    description: StringOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileOrganizationProvider(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    description: StringOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceDedicatedInternet(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    status: DropdownOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class ProfileServiceGeneric(LineageSource, CoreProfile, CoreNode):
    profile_name: String
    profile_priority: IntegerOptional
    related_nodes: RelationshipManager
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class TemplateDcimDevice(LineageSource, CoreNode, CoreObjectTemplate, TemplateDcimGenericDevice):
    template_name: String
    index: IntegerOptional
    status: DropdownOptional
    role: DropdownOptional
    description: StringOptional
    os_version: StringOptional
    serial: StringOptional
    position: IntegerOptional
    rack_face: DropdownOptional
    related_nodes: RelationshipManager
    artifacts: RelationshipManager
    platform: RelatedNode
    tags: RelationshipManager
    primary_address: RelatedNode
    interfaces: RelationshipManager
    device_type: RelatedNode
    location: RelatedNode
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class TemplateDcimInterfaceL2(LineageSource, CoreNode, CoreObjectComponentTemplate, TemplateDcimInterface):
    template_name: String
    status: DropdownOptional
    role: DropdownOptional
    l2_mode: StringOptional
    description: StringOptional
    speed: Integer
    enabled: BooleanOptional
    mtu: IntegerOptional
    name: String
    related_nodes: RelationshipManager
    untagged_vlan: RelatedNode
    tagged_vlan: RelationshipManager
    tags: RelationshipManager
    device: RelatedNode
    service: RelatedNode
    connector: RelatedNode
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class TemplateDcimInterfaceL3(LineageSource, CoreNode, CoreObjectComponentTemplate, TemplateDcimInterface):
    template_name: String
    role: DropdownOptional
    status: DropdownOptional
    description: StringOptional
    speed: Integer
    enabled: BooleanOptional
    mtu: IntegerOptional
    name: String
    related_nodes: RelationshipManager
    ip_addresses: RelationshipManager
    tags: RelationshipManager
    device: RelatedNode
    service: RelatedNode
    connector: RelatedNode
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class TemplateIpamIPAddress(LineageSource, CoreNode, CoreObjectComponentTemplate):
    template_name: String
    fqdn: StringOptional
    description: StringOptional
    address: IPHost
    related_nodes: RelationshipManager
    service: RelatedNode
    interface: RelatedNode
    ip_namespace: RelatedNode
    ip_prefix: RelatedNode
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager


class TemplateIpamVLAN(LineageSource, CoreNode, CoreObjectComponentTemplate):
    template_name: String
    role: DropdownOptional
    name: String
    vlan_id: Integer
    status: Dropdown
    description: StringOptional
    related_nodes: RelationshipManager
    service: RelatedNode
    prefixes: RelationshipManager
    location: RelationshipManager
    l2domain: RelatedNode
    member_of_groups: RelationshipManager
    subscriber_of_groups: RelationshipManager
